### ISSUE TITLE
Ownership 

### ISSUE THREAD

**Issue by 304NotModified** [304NotModified/Fody.Stamp#26]
Hi @SimonCropp!

I'm thinking to volunteer for the ownership (if someone else is also interested, please reply - I like working in teams!) 

Could we arrange a transfer of your knowledge (how to build, how to publish, (build) scripts,  which projects to edit, caveats etc?)  - on chat or mail?

**Comment by SimonCropp** [comment]
All tgat is fine. Although i generally recommend peopke use gitversion these  days https://github.com/GitTools/GitVersion

**Comment by SimonCropp** [comment]
i cant transfer while you have a fork

**Comment by 304NotModified** [comment]
Hi @SimonCropp 

Thanks!

I'm a bit more busy compared to a few months ago. I still have interest in maintaining it, but I think it's a good step to first check the code in-depth and then transfer the knowledge.

I will try to do that this week/weekend.

**Comment by 304NotModified** [comment]
@SimonCropp we are still using the lib, with pleasure.

I would like to maintain this repo, but first I'm I like to know:

- what is the code inside Fody/PeImage and /Fody/VersionResources?
- this code is more complicated compared to https://github.com/krk/Stamp. (SVN Stamp). Any idea why?

**Comment by SimonCropp** [comment]
> Fody/PeImage and /Fody/VersionResources

you are best of asking @qmfrederik https://github.com/Fody/Stamp/pull/19

i have not looked at SVN stamp. so cant speak to it

**Comment by 304NotModified** [comment]
@SimonCropp it has been a long time, and I like to fix https://github.com/Fody/Stamp/issues/27. Also I like to merge some PRs

So I think it would be nice if I could transfer it, I have a fork, but I prefer to be owner of the current repo (so PRs stay intact).

**Comment by qmfrederik** [comment]
re: what is the code inside Fody/PeImage and /Fody/VersionResources?

It is the managed equivalent of `verpatch.exe`. It patches the executable to add version information. It's what you see when your right-click a file in Windows Explorer and open the file properties.

Replacing `verpatch.exe` with managed code allowed us to use Fody/Stamp on macOS and Linux using Mono.

Lots has changed since we opened that PR two years and a half ago; we now use .NET Core together with NerdBank.GitVersion, so we don't rely on Fody/Stamp any more.

**Comment by 304NotModified** [comment]
Thanks @qmfrederik :)

**Comment by SimonCropp** [comment]
@304NotModified i dont think i can transfer ownership to u while u have an active fork

**Comment by 304NotModified** [comment]
I removed my fork

**Comment by SimonCropp** [comment]
what is your nuget name?

**Comment by 304NotModified** [comment]
The same as Github: https://www.nuget.org/profiles/304NotModified

**Comment by SimonCropp** [comment]
done

**Comment by 304NotModified** [comment]
resolved :) Thanks!

**Comment by 304NotModified** [comment]
> what is your nuget name?

@SimonCropp could you please add me to https://www.nuget.org/packages/Stamp.Fody/?
