### ISSUE TITLE
The weaver assembly references an out of date version of Mono.Cecil.dll when using Fody 3

### ISSUE THREAD

**Issue by 304NotModified** [304NotModified/Fody.Stamp#27]
We got the following exception when using Fody 3

> Fody: The weaver assembly 'Stamp.Fody, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll. Expected strong name token of '1C-A0-91-87-7D-12-CA-03' but got '50-CE-BF-1C-CE-B9-D0-5E'. The weaver needs to update to at least version 3.0 of FodyHelpers.

**Comment by 304NotModified** [comment]
yes I was already typing in #26 ;)

**Comment by 304NotModified** [comment]
@SimonCropp I have already a question on this.

The nuspec references Fody, while the packages.config refers FodyCecil. How does that work? 

There is also no FodyCecil 3, so not sure how to update to make this Fody3 compatible.

Thanks!

**Comment by SimonCropp** [comment]
have a look at https://github.com/Fody/BasicFodyAddin

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue

**Comment by hali15845** [comment]
@304NotModified I'm running into this issue. Any updates ? Would love to use this weaver!

**Comment by SimonCropp** [comment]
@hali15845 perhaps submit a pull request that fixes this problem

**Comment by 304NotModified** [comment]
@hali15845 which platform? I had some trouble to get this addon working the new CSProj format.

**Comment by 304NotModified** [comment]
closed by #52
