### ISSUE TITLE
When will you upgrade the vesion of dependency assembly Fody to 3.3?

### ISSUE THREAD

**Issue by chucklu** [304NotModified/Fody.Stamp#50]
Currently(2018-11-22), the latest version of Fody is 3.3, and the nuget release package can only works with 2.* version of Fody.
Do you have a plan to support Fody with version 3.*？

**Comment by 304NotModified** [comment]
see https://github.com/304NotModified/Fody.Stamp/issues/27

there is no date yet. Haven't found time to fix it, so any help would be awesome :)

**Comment by chucklu** [comment]
If you want , I can try to upgrade the Fody to latest 2.* version.(2.5.0).

I encounter problem when use 2.0.3 version of Fody
https://github.com/304NotModified/Fody.Stamp/issues/49

**Comment by chucklu** [comment]
close this issue according https://github.com/304NotModified/Fody.Stamp/pull/52
